export const CHIAPAS_MUNICIPIOS = {
  "acacoyagua": 1,
  "acala": 2,
  "acapetahua": 3,
  "aldama": 112,
  "altamirano": 4,
  "amatan": 5,
  "amatenango de la frontera": 6,
  "amatenango del valle": 7,
  "angel albino corzo": 8,
  "arriaga": 9,
  "capitan luis angel vidal": 119,
  "catazaja": 16,
  "chalchihuitan": 22,
  "chamula": 23,
  "chanal": 24,
  "chapultenango": 25,
  "chenalho": 26,
  "chiapa de corzo": 27,
  "bejucal de ocampo": 10,
  "huixtla": 40,
  "ixhuatan": 42,
  "ixtacomitan": 43,
  "ixtapa": 44,
  "ixtapangajoya": 45,
  "jiquipilas": 46,
  "jitotol": 47,
  "juarez": 48,
  "la concordia": 20,
  "bella vista": 11,
  "benemerito de las americas": 113,
  "berriozabal": 12,
  "bochil": 13,
  "cacahoatan": 15,
  "chiapilla": 28,
  "chicoasen": 29,
  "chicomuselo": 30,
  "chilon": 31,
  "cintalapa": 17,
  "coapilla": 18,
  "comitan de dominguez": 19,
  "copainala": 21,
  "el bosque": 14,
  "el parral": 121,
  "el porvenir": 70,
  "emiliano zapata": 122,
  "escuintla": 32,
  "francisco leon": 33,
  "frontera comalapa": 34,
  "frontera hidalgo": 35,
  "honduras de la sierra": 124,
  "huehuetan": 37,
  "huitiupan": 38,
  "huixtan": 39,
  "la grandeza": 36,
  "la independencia": 41,
  "la libertad": 50,
  "la trinitaria": 99,
  "larrainzar": 49,
  "las margaritas": 52,
  "las rosas": 74,
  "mapastepec": 51,
  "maravilla tenejapa": 114,
  "marques de comillas": 115,
  "mazapa de madero": 53,
  "mazatan": 54,
  "metapa": 55,
  "mezcalapa": 123,
  "mitontic": 56,
  "montecristo de guerrero": 116,
  "motozintla": 57,
  "rincon chamula san pedro": 120,
  "sabanilla": 75,
  "salto de agua": 76,
  "nicolas ruiz": 58,
  "ocosingo": 59,
  "simojovel": 82,
  "sitala": 83,
  "ocotepec": 60,
  "ocozocoautla de espinosa": 61,
  "ostuacan": 62,
  "osumacinta": 63,
  "oxchuc": 64,
  "palenque": 65,
  "pantelho": 66,
  "pantepec": 67,
  "pichucalco": 68,
  "pijijiapan": 69,
  "pueblo nuevo solistahuacan": 71,
  "socoltenango": 84,
  "solosuchiapa": 85,
  "rayon": 72,
  "reforma": 73,
  "san andres duraznal": 117,
  "san cristobal de las casas": 77,
  "san fernando": 78,
  "san juan cancuc": 79,
  "san lucas": 80,
  "santiago el pinar": 118,
  "siltepec": 81,
  "soyalo": 86,
  "suchiapa": 87,
  "suchiate": 88,
  "sunuapa": 89,
  "tapachula": 90,
  "tapalapa": 91,
  "tapilula": 92,
  "tecpatan": 93,
  "tenejapa": 94,
  "teopisca": 95,
  "tila": 96,
  "tonala": 97,
  "totolapa": 98,
  "tumbala": 100,
  "tuxtla chico": 101,
  "tuxtla gutierrez": 102,
  "tuzantan": 103,
  "tzimol": 104,
  "union juarez": 105,
  "venustiano carranza": 106,
  "villa corzo": 108,
  "villacomaltitlan": 107,
  "villaflores": 109,
  "yajalon": 110,
  "zinacantan": 111
};